# Generated by Django 5.2.10 on 2026-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
